(projectile-global-mode)
(setq projectile-enable-caching t)
(setq projectile-switch-project-action 'projectile-dired)
(setq projectile-switch-project-action 'projectile-find-dir)
(setq projectile-find-dir-includes-top-level t)
;;(setq projectile-completion-system 'grizzl)
(setq projectile-keymap-prefix (kbd "C-c C-p"))
